# Generated by Django 4.0.4 on 2022-06-03 20:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0005_alter_m_cliente_fecharegistro_alter_m_producto_fecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 20, 45, 17, 355480))),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('m_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.m_cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Clientes Articulo',
                'verbose_name_plural': 'Pedido de Clientes articulos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='T_Pedidoarticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('m_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='venta.m_producto')),
                ('pedido', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='delivery.t_pedido')),
            ],
            options={
                'verbose_name': 'Pedido de detalle Articulo',
                'verbose_name_plural': 'Pedido de detalle articulos',
                'ordering': ['id'],
            },
        ),
    ]
