# Generated by Django 4.0.4 on 2022-06-03 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_pedido',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 3, 20, 55, 4, 113009)),
        ),
    ]
