# Generated by Django 4.0.4 on 2022-04-23 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_DevolucionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 610040))),
                ('motivoanular', models.CharField(blank=True, default=' ', max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('t_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.t_compra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución T_Compra',
                'verbose_name_plural': 'Devolución T_Compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='T_DevolucionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 608040))),
                ('motivoanular', models.CharField(blank=True, default=' ', max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('t_factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.t_factura')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de Factura',
                'verbose_name_plural': 'Devolución de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='T_DevolucionDetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cantidad', models.IntegerField()),
                ('cantidaddev', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('m_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='venta.m_producto')),
                ('t_devolucionfactura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devolucion.t_devolucionfactura')),
            ],
            options={
                'verbose_name': 'Detalle devolucion Factura',
                'verbose_name_plural': 'Detalle devolucion Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='T_DevoluciondetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cantidad', models.IntegerField()),
                ('cantidaddev', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('m_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='venta.m_producto')),
                ('t_devolucioncompra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devolucion.t_devolucioncompra')),
            ],
            options={
                'verbose_name': 'Detalle devolucion compra',
                'verbose_name_plural': 'Detalle devolucion compra',
                'ordering': ['id'],
            },
        ),
    ]
