# Generated by Django 4.0.4 on 2022-05-04 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devolucion', '0003_alter_t_devolucioncompra_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_devolucioncompra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 17, 14, 26, 58793)),
        ),
        migrations.AlterField(
            model_name='t_devolucionfactura',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 17, 14, 26, 57795)),
        ),
    ]
