# Generated by Django 4.0.4 on 2022-04-23 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PROVEEDOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='EMPRESA')),
                ('direccion', models.CharField(default='', max_length=200, verbose_name='DIRECCION')),
                ('sitioweb', models.CharField(default='', max_length=200, verbose_name='DIRECCION')),
                ('telefono', models.CharField(default='', max_length=10, verbose_name='TELEFONO')),
                ('fecharegistro', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 605042))),
                ('ced_ruc', models.CharField(default='', max_length=13, verbose_name='Cedula o Ruc')),
                ('email', models.CharField(default='', max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='T_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 605042))),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('m_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.m_proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'T_Compra',
                'verbose_name_plural': 'T_Compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='T_Compradetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('m_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='venta.m_producto')),
                ('t_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compra.t_compra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalle de Compra',
                'ordering': ['id'],
            },
        ),
    ]
