# Generated by Django 4.0.4 on 2022-04-23 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_proveedor',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 31, 18, 681728)),
        ),
        migrations.AlterField(
            model_name='t_compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 31, 18, 682728)),
        ),
    ]
