# Generated by Django 4.0.4 on 2022-05-04 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_m_proveedor_fecharegistro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_proveedor',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 17, 14, 26, 55796)),
        ),
        migrations.AlterField(
            model_name='t_compra',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 4, 17, 14, 26, 55796)),
        ),
    ]
