# Generated by Django 4.0.4 on 2022-04-23 17:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_CLIENTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=200, verbose_name='Nombre')),
                ('direccion', models.CharField(default='', max_length=200, verbose_name='DIRECCION')),
                ('sitioweb', models.CharField(default='', max_length=200, verbose_name='sitio web')),
                ('telefono', models.CharField(default='', max_length=10, verbose_name='TELEFONO')),
                ('ced_ruc', models.CharField(default='', max_length=13, verbose_name='Cedula o Ruc')),
                ('fecharegistro', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 601045), verbose_name='fecha de registro')),
                ('email', models.CharField(default='', max_length=200, verbose_name='Email')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='M_Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='M_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default=' ', max_length=200)),
                ('nombre', models.CharField(default=' ', max_length=200)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('stock', models.IntegerField(default=0)),
                ('stockmin', models.IntegerField(default=0)),
                ('stockmax', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='articulo/%Y/%m/%d/')),
                ('promocion', models.DecimalField(decimal_places=0, default=0, max_digits=19)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 603043))),
                ('puntoroden', models.IntegerField(default=0)),
                ('iva', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('m_marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.m_marca')),
            ],
            options={
                'verbose_name': 'M_Producto',
                'verbose_name_plural': 'M_Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='M_TipoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Categoria',
                'verbose_name_plural': 'Tipo Categorias',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='M_Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Descripción')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='T_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 30, 50, 604060))),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('m_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.m_cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'T_Factura',
                'verbose_name_plural': 'T_Factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='T_Facturadetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.BooleanField(default=True)),
                ('m_producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='venta.m_producto')),
                ('t_factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venta.t_factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalle de Factura',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='m_producto',
            name='m_tipocategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.m_tipocategoria'),
        ),
        migrations.AddField(
            model_name='m_producto',
            name='m_ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='venta.m_ubicacion'),
        ),
    ]
