# Generated by Django 4.0.4 on 2022-04-23 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cliente',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 31, 18, 677732), verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='m_producto',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 31, 18, 679730)),
        ),
        migrations.AlterField(
            model_name='t_factura',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 31, 18, 680730)),
        ),
    ]
