# Generated by Django 4.0.4 on 2022-04-24 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_m_cliente_fecharegistro_alter_m_producto_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_cliente',
            name='fecharegistro',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 24, 20, 29, 4, 662170), verbose_name='fecha de registro'),
        ),
        migrations.AlterField(
            model_name='m_producto',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 24, 20, 29, 4, 664169)),
        ),
        migrations.AlterField(
            model_name='t_factura',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 24, 20, 29, 4, 665169)),
        ),
    ]
